#
# Docker file for Celery in a Bottle v1.0
#
FROM python:3.8
LABEL maintainer="4_squad"
LABEL version="1.0"
LABEL description="Celery worker"

# creating the environment
COPY . /app
# setting the workdir
WORKDIR /app

# environmental variable used to understand if docker is running. 
# If not, redis server and celery worker must be started locally.
ENV DOCKER_IN_USE=yes

# installing all requirements
RUN ["pip", "install", "-r", "requirements.prod.txt"]

# Main command
CMD ["celery", "-A", "mib.background", "worker", "-l", "INFO", "-B"]