version: 2.1
orbs:
  codecov: codecov/codecov@3.2.0
 
jobs:
  toxify:
      docker:
        - image: circleci/python:3.9
      steps:
        - checkout
        - run: 
            name: Install tox
            command: |
              pip install tox
        - run: 
            name: Launch tox (run tests and collect coverage)
            command: |
              tox -e py39
        - codecov/upload
 
workflows:
  version: 2.1
  mib_users:
    jobs:
      - toxify